NumPy is the essential library for numerical computations in Python! Think of NumPy as a toolbox specifically designed for working with numbers in a fun and efficient way.

Imagine a Snake Block Game, but with Numbers!

Regular Python lists can store numbers, but NumPy creates special arrays where all the numbers are of the same kind, like a team with matching uniforms. This makes NumPy arrays super fast for calculations.

---

#### Here's how to create a NumPy array:

In [8]:
import numpy as np  # Importing NumPy, like bringing the toolbox

# Creating an array of your favorite numbers (all numbers are integers here)
numbers_array = np.array([3, 7, 9, 11])

# Printing the array, like showing your team
print(numbers_array)


[ 3  7  9 11]


---

#### Accessing Elements: Like Picking Numbers from Your Team

You can access specific numbers in the array using square brackets [] with their position, just like picking a player from your team by their jersey number:

In [2]:
# Get the second number (remember counting starts from 0)
second_number = numbers_array[1]
print(second_number)  # This will output 7


7


---

#### Slicing: Choosing Parts of the Team

Imagine you want the first two numbers to tackle a challenge. NumPy slicing lets you grab a portion of the array using a colon ::

In [3]:
# Get the first two numbers (0th and 1st position)
first_two = numbers_array[0:2]  # colon means "up to, but not including" the end index
print(first_two)  # This will output [3 7]


[3 7]


---

#### Superpowers: Mathematical Operations on the Whole Team!

NumPy shines when you perform operations on the entire array at once. It's like training your whole team together!

In [4]:
# Add 5 to all the numbers (element-wise addition)
added_array = numbers_array + 5
print(added_array)  # This will output [8 12 14 16]

# Double all the numbers
doubled_array = numbers_array * 2
print(doubled_array)  # This will output [6 14 18 22]


[ 8 12 14 16]
[ 6 14 18 22]


---

#### Different Types of Teams (Data Types):

NumPy can handle different types of numbers, not just integers. You can create arrays of floats (numbers with decimals), booleans (True/False), or even text characters:

In [5]:
# Array of decimals
decimals_array = np.array([3.14, 2.72])
print(decimals_array)

# Array of True/False (booleans)
boolean_array = np.array([True, False, True])
print(boolean_array)

[3.14 2.72]
[ True False  True]


---

#### Bonus Tip: Creating Arrays in Different Ways

There are other ways to create NumPy arrays, like using the range function to generate a sequence of numbers:

In [6]:
# Array of numbers from 1 to 5 (excluding 6)
range_array = np.arange(1, 6)
print(range_array)  # This will output [1 2 3 4 5]


[1 2 3 4 5]
